UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-педиатрия' WHERE full_name = 'Приходько Елена Александровна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-педиатрия' WHERE full_name = 'Раевская Татьяна Александровна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-педиатрия' WHERE full_name = 'Сорокина Анна Васильевна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-педиатрия' WHERE full_name = 'Хорошко Лариса Александровна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-акушерство и гинекология' WHERE full_name = 'Реут Лариса Федоровна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-хирургия детская' WHERE full_name = 'Чепурная Наталья Владимировна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Вторая-терапия' WHERE full_name = 'Клименко Оксана Сергеевна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-дерматовенерология' WHERE full_name = 'Гненная Виктория Михайловна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Вторая-терапия' WHERE full_name = 'Виноград Наталья Владимировна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-терапия' WHERE full_name = 'Медко Сергей Григорьевич';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-дерматовенерология' WHERE full_name = 'Волохова Елена Игоревна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-общая практика семейная медицина' WHERE full_name = 'Лукьяненко Олеся Владимировна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-педиатрия' WHERE full_name = 'Шурупов Вячеслав Михайлович';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-терапия' WHERE full_name = 'Самойленко Лидия Александровна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-терапия' WHERE full_name = 'Михайленко Лариса Сергеевна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-педиатрия' WHERE full_name = 'Дрыга Елена Владимировна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Высшая-педиатрия' WHERE full_name = 'Панасюк Наталья Васильевна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-терапия' WHERE full_name = 'Чернявская Элла Николаевна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Вторая-общая практика семейная медицина' WHERE full_name = 'Красникова Ирина Геннадиевна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-акушерство и гинекология' WHERE full_name = 'Курганникова Любовь Анатольевна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-общая практика семейная медицина' WHERE full_name = 'Селиверстова Анна Александровна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-общая практика семейная медицина' WHERE full_name = 'Клопотар Татьяна Викторовна';
UPDATE t_p30358746_hospital_website_red.doctors SET category = 'Первая-педиатрия' WHERE full_name = 'Раевская Татьяна Ивановна';